### ISSUE TITLE
Compatibility with Debian or other Linux x86 System

### ISSUE THREAD

**Issue by hugochen168** [strangebit-io/hip-vpls-hw#1]
Hi Dmitriy
     I meet some deployment issues on Debian. I guess it's a library issue. Can you advise? Thanks.
     
     _File "/opt/hip-vpls/switchd.py", line 51, in <module>
    from hiplib import hlib
  File "/opt/hip-vpls/hiplib/hlib.py", line 56, in <module>
    from hiplib.utils.hi import RSAHostID, ECDSAHostID, ECDSALowHostID
  File "/opt/hip-vpls/hiplib/utils/hi.py", line 27, in <module>
    from hiplib.utils.misc import Math
  File "/opt/hip-vpls/hiplib/utils/misc.py", line 194, in <module>
    from hiplib.crypto.factory import HMACFactory, SymmetricCiphersFactory
  File "/opt/hip-vpls/hiplib/crypto/factory.py", line 31, in <module>
    from hiplib.crypto.symmetric import AES128CBCCipher, AES256CBCCipher, NullCipher
  File "/opt/hip-vpls/hiplib/crypto/symmetric.py", line 25, in <module>
    lib = cdll.LoadLibrary('/opt/hip-vpls/hiplib/crypto/aeslib.so')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /opt/hip-vpls/hiplib/crypto/aeslib.so: cannot open shared object file: No such file or directory_

**Comment by dmitriykuptsov** [comment]
Hi, yes you need to recompile the hmac and aes library for for your platform. Compile these two libraries for x86 (the CPUneeds to support Intel NI aes and hmac instructions!) and place both so files under crypto module folderdmitriykuptsov/hw-crypto-sha2-ni: SHA256 NI implementationgithub.comhttps://github.com/dmitriykuptsov/hw-crypto-aes-ni/blob/main/makefileAfter that you should be able to run the hip-vpls switch with no problemSent from my iPhoneOn 17 Apr 2024, at 23:36, Jellyfish ***@***.***> wrote:﻿
Hi Dmitriy
I meet some deployment issues on Debian. I guess it's a library issue. Can you advise? Thanks.
 _File "/opt/hip-vpls/switchd.py", line 51, in <module>
from hiplib import hlib

File "/opt/hip-vpls/hiplib/hlib.py", line 56, in 
from hiplib.utils.hi import RSAHostID, ECDSAHostID, ECDSALowHostID
File "/opt/hip-vpls/hiplib/utils/hi.py", line 27, in 
from hiplib.utils.misc import Math
File "/opt/hip-vpls/hiplib/utils/misc.py", line 194, in 
from hiplib.crypto.factory import HMACFactory, SymmetricCiphersFactory
File "/opt/hip-vpls/hiplib/crypto/factory.py", line 31, in 
from hiplib.crypto.symmetric import AES128CBCCipher, AES256CBCCipher, NullCipher
File "/opt/hip-vpls/hiplib/crypto/symmetric.py", line 25, in 
lib = cdll.LoadLibrary('/opt/hip-vpls/hiplib/crypto/aeslib.so')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/ctypes/init.py", line 454, in LoadLibrary
return self._dlltype(name)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/ctypes/init.py", line 376, in init
self._handle = _dlopen(self.name, mode)
^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /opt/hip-vpls/hiplib/crypto/aeslib.so: cannot open shared object file: No such file or directory

**Comment by dmitriykuptsov** [comment]
Also make sure that the libraries are copied to the hip-vpls folder under opt it seems like they are not currently (also i think thatcurrent repo has compiled libraries already they are just not copied by the deployment script, i will check)Best,DmitriySent from my iPhoneOn 18 Apr 2024, at 09:22, Dmitriy Kuptsov ***@***.***> wrote:﻿Hi, yes you need to recompile the hmac and aes library for for your platform. Compile these two libraries for x86 (the CPUneeds to support Intel NI aes and hmac instructions!) and place both so files under crypto module folder<hw-crypto-sha2-ni.png>dmitriykuptsov/hw-crypto-sha2-ni: SHA256 NI implementationgithub.comhttps://github.com/dmitriykuptsov/hw-crypto-aes-ni/blob/main/makefileAfter that you should be able to run the hip-vpls switch with no problemSent from my iPhoneOn 17 Apr 2024, at 23:36, Jellyfish ***@***.***> wrote:﻿
Hi Dmitriy
I meet some deployment issues on Debian. I guess it's a library issue. Can you advise? Thanks.
 _File "/opt/hip-vpls/switchd.py", line 51, in <module>
from hiplib import hlib

File "/opt/hip-vpls/hiplib/hlib.py", line 56, in 
from hiplib.utils.hi import RSAHostID, ECDSAHostID, ECDSALowHostID
File "/opt/hip-vpls/hiplib/utils/hi.py", line 27, in 
from hiplib.utils.misc import Math
File "/opt/hip-vpls/hiplib/utils/misc.py", line 194, in 
from hiplib.crypto.factory import HMACFactory, SymmetricCiphersFactory
File "/opt/hip-vpls/hiplib/crypto/factory.py", line 31, in 
from hiplib.crypto.symmetric import AES128CBCCipher, AES256CBCCipher, NullCipher
File "/opt/hip-vpls/hiplib/crypto/symmetric.py", line 25, in 
lib = cdll.LoadLibrary('/opt/hip-vpls/hiplib/crypto/aeslib.so')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/ctypes/init.py", line 454, in LoadLibrary
return self._dlltype(name)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/ctypes/init.py", line 376, in init
self._handle = _dlopen(self.name, mode)
^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /opt/hip-vpls/hiplib/crypto/aeslib.so: cannot open shared object file: No such file or directory

**Comment by dmitriykuptsov** [comment]
You might probably be intrested in the following set up as well (it has everything compiled for Intel CPU with NI instructions) and has controller

https://github.com/dmitriykuptsov/hip-vpls-controller


https://github.com/dmitriykuptsov/hip-vpls-hw-with-controller

All the best,
Dmitriy

**Comment by dmitriykuptsov** [comment]
Here are the libraries for Intel x86

https://github.com/dmitriykuptsov/hw-crypto-sha2-ni

https://github.com/dmitriykuptsov/hw-crypto-aes-ni

**Comment by dmitriykuptsov** [comment]
Ok i have got it the path that is expected by hip-vpls is /opt/hip-vpls/hiplib/crypto/aeslib.so

Make sure you deploy the code there currently you are running under some other directory

**Comment by dmitriykuptsov** [comment]
Also make sure you use deployment script to rollout the system. pycryptodome should be installed globally. The root cause was the incorrect path for so files. Closing the ticket

**Comment by hugochen168** [comment]
I've realized that Debian 12 is not able to achieve pip install directly, you have to use the following command "pip install --break-system-packages pycryptodome". However, the new issue coming out.

python3 switchd.py 
Traceback (most recent call last):
  File "/opt/hip-vpls/switchd.py", line 51, in <module>
    from hiplib import hlib
  File "/opt/hip-vpls/hiplib/hlib.py", line 56, in <module>
    from hiplib.utils.hi import RSAHostID, ECDSAHostID, ECDSALowHostID
  File "/opt/hip-vpls/hiplib/utils/hi.py", line 27, in <module>
    from hiplib.utils.misc import Math
  File "/opt/hip-vpls/hiplib/utils/misc.py", line 194, in <module>
    from hiplib.crypto.factory import HMACFactory, SymmetricCiphersFactory
  File "/opt/hip-vpls/hiplib/crypto/factory.py", line 31, in <module>
    from hiplib.crypto.symmetric import AES128CBCCipher, AES256CBCCipher, NullCipher
  File "/opt/hip-vpls/hiplib/crypto/symmetric.py", line 25, in <module>
    lib = cdll.LoadLibrary('/opt/hip-vpls/hiplib/crypto/aeslib.so')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /opt/hip-vpls/hiplib/crypto/aeslib.so: cannot open shared object file: No such file or directory

**Comment by hugochen168** [comment]
https://github.com/strangebit-io/hip-vpls-hw/issues/1#issuecomment-2063322839

**Comment by hugochen168** [comment]
Hi Dmitriy     Actually, the issue is still there. Just wondering have you tried it on Debian 12 or an Intel x86-based system? Thanks a lot.

Traceback (most recent call last):

  File "/opt/hip-vpls/switchd.py", line 51, in <module>

    from hiplib import hlib

  File "/opt/hip-vpls/hiplib/hlib.py", line 56, in <module>

    from hiplib.utils.hi import RSAHostID, ECDSAHostID, ECDSALowHostID

  File "/opt/hip-vpls/hiplib/utils/hi.py", line 27, in <module>

    from hiplib.utils.misc import Math

  File "/opt/hip-vpls/hiplib/utils/misc.py", line 194, in <module>

    from hiplib.crypto.factory import HMACFactory, SymmetricCiphersFactory

  File "/opt/hip-vpls/hiplib/crypto/factory.py", line 31, in <module>

    from hiplib.crypto.symmetric import AES128CBCCipher, AES256CBCCipher, NullCipher

  File "/opt/hip-vpls/hiplib/crypto/symmetric.py", line 25, in <module>

    lib = cdll.LoadLibrary('/opt/hip-vpls/hiplib/crypto/aeslib.so')

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary

    return self._dlltype(name)

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__

    self._handle = _dlopen(self._name, mode)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^

OSError: /opt/hip-vpls/hiplib/crypto/aeslib.so: cannot open shared object file: No such file or directory



//Hugo 
 
 在 2024年4月18日 星期四 下午04:32:28 [GMT+8]， Dmitriy ***@***.***> 寫道： 







Also make sure you use deployment script to rollout the system. pycryptodome should be installed globally. The root cause was the incorrect path for so files. Closing the ticket
